// grpc-facts.js — which gRPC services a source file SERVES, and which it CALLS.
//
// The `.proto` next door gives the contract: every operation's globally unique wire path,
// `/<package>.<Service>/<Method>`. This file supplies the other half — which repository is on
// which end of it — so `cross-repo-edge-resolver.js` can join them.
//
// THE TRAP THAT DEFINES THIS FILE'S DESIGN
// ----------------------------------------
// protoc generates, for ONE .proto, a single module containing a client stub and a server base
// for EVERY service in that file. Real fleets then vendor that module into each service's own
// tree — Online Boutique ships `demo_pb2_grpc.py` inside all four Python services and
// `genproto/demo_grpc.pb.go` inside all four Go services, each copy naming all nine services.
//
// A detector that greps identifiers therefore concludes that **every service calls every other
// service**: a dense, confident, entirely false graph. Measured on that repo, service-level
// grepping without this exclusion yields 9x9 instead of the real handful of dependencies.
//
// So: **generated code is never evidence of a dependency.** It is the contract's materialisation
// and is present whether or not a line of the service uses it. Only hand-written files are read.
// Generation is detected by the convention the generators themselves publish — Go specifies the
// marker exactly (`^// Code generated .* DO NOT EDIT\.$`, golang.org/s/generatedcode), and
// protoc's other plugins emit an equivalent banner — plus the filename conventions each plugin
// is documented to use.
//
// NAMING IS SPEC-DERIVED, NOT PATTERN-MINED
// -----------------------------------------
// Every marker below is mandated by a protoc plugin and documented in the gRPC generated-code
// reference for that language, so it holds for any codebase, not just the one it was checked
// against:
//
//   Go      protoc-gen-go-grpc   server `Register<S>Server(`      client `New<S>Client(`
//   Python  grpcio-tools         server `add_<S>Servicer_to_server`, `<S>Servicer`
//                                client `<S>Stub(`
//   Java    protoc-gen-grpc-java server `<S>Grpc.<S>ImplBase`      client `<S>Grpc.new*Stub`,
//                                                                        `<S>Grpc.<S>*Stub`
//   C#      Grpc.Tools           server `<S>.<S>Base`             client `<S>.<S>Client`
//   Node    @grpc/grpc-js        dynamic: server `addService(<x>.<S>.service`
//                                         client `new <x>.<S>(`
//
// Node is the weak one and is marked as such: `@grpc/proto-loader` resolves service names at
// runtime from a variable, so a service referenced through an alias this scanner cannot follow is
// missed. It under-reports rather than guessing.
//
// A file that both serves and calls the same service (a server module that also holds a test
// client) is reported as both; deduplication is the caller's business.

'use strict';

const path = require('path');

// Go's convention is normative (golang.org/s/generatedcode); the others emit an equivalent
// banner. Checked against the head of the file only — a comment deep inside a hand-written file
// that happens to quote the banner is not a generation marker.
const GENERATED_BANNER = /^\s*(\/\/|#|\/\*)?\s*(Code generated .*DO NOT EDIT|Generated by the protocol buffer compiler|Generated by the gRPC .* protocol compiler|@generated)/im;

const GENERATED_NAME = /(\.pb\.go|_pb2\.py|_pb2_grpc\.py|\.pb\.cc|\.pb\.h|_pb\.js|_grpc_pb\.js|_pb\.d\.ts|\.pb\.swift|_pb2_grpc\.pyi|_pb2\.pyi)$/i;
const GENERATED_DIR = /(^|\/)(genproto|generated|gen|obj|build|node_modules|vendor|target|__pycache__)(\/|$)/i;

/** True when a file is protoc/plugin output rather than something a person wrote. */
function isGeneratedProtoArtifact(relPath, content) {
  const p = (relPath || '').replace(/\\/g, '/');
  if (GENERATED_NAME.test(p)) return true;
  // `<Service>Grpc.java` is protoc-gen-grpc-java's output name and carries no other marker in
  // some build layouts.
  if (/(^|\/)[A-Za-z0-9_]+Grpc\.java$/.test(p)) return true;
  if (GENERATED_DIR.test(p)) return true;
  const head = (content || '').slice(0, 2000);
  return GENERATED_BANNER.test(head);
}

const LANG_BY_EXT = {
  '.go': 'go', '.py': 'python', '.java': 'java', '.kt': 'java',
  '.cs': 'csharp', '.js': 'node', '.mjs': 'node', '.cjs': 'node',
  '.ts': 'node', '.tsx': 'node', '.jsx': 'node',
};

// Each entry: [regex, capture-group-index-of-service-name]
const SERVE_PATTERNS = {
  go: [[/\bRegister([A-Z][A-Za-z0-9_]*?)Server\s*\(/g, 1]],
  python: [
    [/\badd_([A-Z][A-Za-z0-9_]*?)Servicer_to_server\b/g, 1],
    [/\bclass\s+[A-Za-z0-9_]+\s*\(\s*[A-Za-z0-9_.]*?([A-Z][A-Za-z0-9_]*?)Servicer\s*\)/g, 1],
  ],
  java: [
    [/\b([A-Z][A-Za-z0-9_]*?)Grpc\s*\.\s*\1ImplBase\b/g, 1],
    [/\bextends\s+([A-Z][A-Za-z0-9_]*?)ImplBase\b/g, 1],
  ],
  csharp: [[/\b([A-Z][A-Za-z0-9_]*?)\s*\.\s*\1Base\b/g, 1]],
  node: [[/addService\s*\(\s*[A-Za-z0-9_$.]*?\.([A-Z][A-Za-z0-9_]*?)\s*\.\s*service\b/g, 1]],
};

const CALL_PATTERNS = {
  go: [[/\bNew([A-Z][A-Za-z0-9_]*?)Client\s*\(/g, 1]],
  python: [[/\b([A-Z][A-Za-z0-9_]*?)Stub\s*\(/g, 1]],
  java: [
    [/\b([A-Z][A-Za-z0-9_]*?)Grpc\s*\.\s*new[A-Za-z]*Stub\b/g, 1],
    [/\b([A-Z][A-Za-z0-9_]*?)Grpc\s*\.\s*\1(?:Blocking|Future)?Stub\b/g, 1],
  ],
  csharp: [[/\b([A-Z][A-Za-z0-9_]*?)\s*\.\s*\1Client\b/g, 1]],
  node: [[/\bnew\s+[A-Za-z0-9_$.]*?\.([A-Z][A-Za-z0-9_]*?)\s*\(/g, 1]],
};

function collect(patterns, text) {
  const found = new Map(); // serviceName -> first line
  for (const [re, group] of patterns) {
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      const name = m[group];
      if (!name || name.length < 2) continue;
      if (!found.has(name)) {
        found.set(name, text.slice(0, m.index).split('\n').length);
      }
    }
  }
  return found;
}

/**
 * gRPC roles a single hand-written source file plays.
 *
 * @param {string} relPath repo-relative path
 * @param {string} content file text
 * @param {{knownServices?: Set<string>|Array<string>}} [opts] when supplied, only service names
 *   the contract actually declares are returned. Strongly recommended: it is what stops
 *   `NewHealthClient` / `new Date(` / `Foo.FooClient` from inventing a service that no `.proto`
 *   in the project defines.
 * @returns {{serves: Array<{service,line}>, calls: Array<{service,line}>, generated: boolean,
 *            methodsMentioned: Set<string>}}
 */
function extractGrpcFacts(relPath, content, opts = {}) {
  const empty = { serves: [], calls: [], generated: false, methodsMentioned: new Set() };
  const text = typeof content === 'string' ? content : '';
  if (!text) return empty;

  const lang = LANG_BY_EXT[path.extname(relPath || '').toLowerCase()];
  if (!lang) return empty;

  if (isGeneratedProtoArtifact(relPath, text)) {
    return { ...empty, generated: true };
  }

  const known = opts.knownServices
    ? (opts.knownServices instanceof Set ? opts.knownServices : new Set(opts.knownServices))
    : null;
  const keep = (name) => (known ? known.has(name) : true);

  const servesMap = collect(SERVE_PATTERNS[lang] || [], text);
  const callsMap = collect(CALL_PATTERNS[lang] || [], text);

  const serves = [...servesMap].filter(([n]) => keep(n)).map(([service, line]) => ({ service, line }));
  const calls = [...callsMap].filter(([n]) => keep(n)).map(([service, line]) => ({ service, line }));

  // Method-level refinement. A bare identifier match would be far too loose on its own, so it is
  // only ever consulted for services this file has ALREADY been shown to serve or call — the
  // conjunction is what makes it safe.
  const methodsMentioned = new Set();
  if (opts.methodsByService && (serves.length || calls.length)) {
    for (const { service } of [...serves, ...calls]) {
      for (const method of (opts.methodsByService.get(service) || [])) {
        const re = new RegExp(`(?<![A-Za-z0-9_])${method}\\s*\\(`);
        if (re.test(text)) methodsMentioned.add(`${service}.${method}`);
      }
    }
  }

  return { serves, calls, generated: false, methodsMentioned };
}

// ─── Thrift ──────────────────────────────────────────────────────────────────
//
// Same shape as gRPC and for the same reason: the Thrift compiler's generated names are fixed by
// the compiler, documented per target language, and therefore hold for any codebase.
//
//   Java / Python   server `<S>.Processor`, `<S>.Iface` implementation
//                   client `<S>.Client`
//   Go              server `New<S>Processor(`      client `New<S>Client(`
//   C++             server `<S>Handler`, `<S>Processor`   client `<S>Client`
//   C# (netstd)     server `<S>.IAsync` implementation    client `<S>.Client`
//   Node            server `new <S>.Processor(`           client `createClient(<S>`
//
// The same generated-artifact exclusion applies: `gen-java/`, `gen-py/`, `*_types.py`,
// `<S>.java` under a gen directory are compiler output and name every service in the IDL, so
// reading them would again conclude that everything talks to everything.
const THRIFT_SERVE_PATTERNS = [
  [/\b([A-Z][A-Za-z0-9_]*?)\s*\.\s*Processor\b/g, 1],
  [/\bNew([A-Z][A-Za-z0-9_]*?)Processor\s*\(/g, 1],
  [/\b(?:implements|extends)\s+([A-Z][A-Za-z0-9_]*?)\s*\.\s*(?:Iface|IAsync|AsyncIface)\b/g, 1],
  [/\bclass\s+[A-Za-z0-9_]+\s*\(\s*([A-Z][A-Za-z0-9_]*?)\s*\.\s*Iface\s*\)/g, 1],
  [/\b([A-Z][A-Za-z0-9_]*?)Handler\b/g, 1],
];

const THRIFT_CALL_PATTERNS = [
  [/\b([A-Z][A-Za-z0-9_]*?)\s*\.\s*Client\b/g, 1],
  [/\bNew([A-Z][A-Za-z0-9_]*?)Client\s*\(/g, 1],
  [/\bcreateClient\s*\(\s*([A-Z][A-Za-z0-9_]*)/g, 1],
];

const THRIFT_GENERATED_DIR = /(^|\/)gen-[a-z0-9_]+(\/|$)/i;
const THRIFT_GENERATED_NAME = /(_types\.(py|rb|js)|ttypes\.py|constants\.(py|js))$/i;

function isGeneratedThriftArtifact(relPath, content) {
  const p = (relPath || '').replace(/\\/g, '/');
  if (THRIFT_GENERATED_DIR.test(p) || THRIFT_GENERATED_NAME.test(p)) return true;
  return isGeneratedProtoArtifact(relPath, content);
}

/**
 * Thrift services a hand-written source file SERVES and CALLS. Mirrors extractGrpcFacts, including
 * the `knownServices` gate — without a `.thrift` declaring the name, `FooHandler` and `Bar.Client`
 * would invent services out of ordinary application classes, so the gate is not optional here in
 * the way it is optional for gRPC.
 */
function extractThriftFacts(relPath, content, opts = {}) {
  const empty = { serves: [], calls: [], generated: false };
  const text = typeof content === 'string' ? content : '';
  if (!text) return empty;
  const lang = LANG_BY_EXT[path.extname(relPath || '').toLowerCase()]
    || (/\.(cpp|cc|hpp|h|rb|pl|php)$/i.test(relPath || '') ? 'other' : null);
  if (!lang) return empty;
  if (isGeneratedThriftArtifact(relPath, text)) return { ...empty, generated: true };

  const known = opts.knownServices
    ? (opts.knownServices instanceof Set ? opts.knownServices : new Set(opts.knownServices))
    : null;
  const keep = (name) => (known ? known.has(name) : false); // no contract, no claim

  const serves = [...collect(THRIFT_SERVE_PATTERNS, text)]
    .filter(([n]) => keep(n)).map(([service, line]) => ({ service, line, kind: 'thrift' }));
  const calls = [...collect(THRIFT_CALL_PATTERNS, text)]
    .filter(([n]) => keep(n)).map(([service, line]) => ({ service, line, kind: 'thrift' }));
  return { serves, calls, generated: false };
}

module.exports = { extractGrpcFacts, extractThriftFacts, isGeneratedProtoArtifact, isGeneratedThriftArtifact, LANG_BY_EXT };
