'use strict';

// Deterministic (zero-token) reader for the "why" layer at SYMBOL granularity.
//
// koragraph's DOC nodes are one-per-prose-file: a README, a design note. That
// covers the why of a *project* and says nothing about the why of a *function*.
// The rationale a maintainer actually needs — "this retries because the vendor
// API 502s under load", "do not reorder, the lock must be taken first" — lives
// in docstrings and in NOTE/HACK/WHY comments next to the code, and neither was
// in the graph at all.
//
// This capability most directly serves onboarding: a new engineer's question
// is usually "why", and "why" is not derivable from structure.
//
// Language-aware, because comment syntax is:
//   Python / Ruby      `"""..."""` or `'''...'''` docstring in the body; `#` comments
//   Java / JS / TS / Go / C# / PHP / Rust / Kotlin   `/** ... */` above; `//` comments
//
// Contract: parseRationale(content, lang) -> [{ text, line, kind, ownerLine }]
//   kind      'docstring' | 'comment'
//   ownerLine the declaration line this rationale documents, or null for a
//             file-level one. The caller binds by line span; this parser does
//             not know the node table.

// TODO/FIXME are here alongside the why-markers because "what is unfinished or
// known-broken here" is the same question a newcomer asks, and the length floor
// below keeps the drive-by one-worders out.
const MARKER_RE = /^(?:\/\/|#|\*|<!--)?\s*(NOTE|IMPORTANT|HACK|WHY|RATIONALE|CAVEAT|GOTCHA|WARNING|XXX|TODO|FIXME)\s*[:!-]/i;

// Below this a "docstring" is a label, not an explanation — `"""Forum."""`
// carries nothing the symbol name does not already say.
const MIN_RATIONALE_CHARS = 25;

const BLOCK_COMMENT_LANGS = new Set(['java', 'javascript', 'typescript', 'csharp', 'go', 'php', 'rust', 'dart', 'kotlin', 'scala', 'swift']);
const DOCSTRING_LANGS = new Set(['python']);

// A generated file's module docstring is a revision annotation, not rationale —
// Django/Alembic migrations, protobuf and OpenAPI stubs are the common cases.
const GENERATED_RE = /(?:^|\n)\s*(?:#|\/\/|\*)?\s*(?:auto-?generated|do not edit|generated by|@generated|Code generated by)/i;

function isGenerated(content) {
  return GENERATED_RE.test(content.slice(0, 2000));
}

function clean(text) {
  return text
    .replace(/\r/g, '')
    .split('\n')
    .map((l) => l.replace(/^\s*\*\s?/, '').trim())
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// A declaration line, for attributing a docstring or a preceding block comment
// to the thing it documents. Deliberately loose: the caller narrows by line
// span against real nodes, so a false positive here costs nothing.
const DECL_RE = {
  python: /^\s*(?:async\s+)?(?:def|class)\s+(\w+)/,
  generic: /^\s*(?:(?:public|private|protected|internal|export|default|static|final|abstract|async|func|fn|def|const|var|let)\s+)*(?:class|interface|enum|struct|trait|record|function|func|fn|def)\s+(\w+)/,
};

function declarationAt(line, lang) {
  const re = lang === 'python' ? DECL_RE.python : DECL_RE.generic;
  const m = re.exec(line);
  if (m) return m[1];
  // Java/C# methods have no leading keyword — `public Owner findOwner(int id) {`
  if (lang !== 'python' && /^\s*(?:@\w+\s*)*(?:public|private|protected)\s+[\w<>\[\],.\s]+\s+(\w+)\s*\(/.test(line)) {
    return /(\w+)\s*\(/.exec(line)[1];
  }
  return null;
}

function parsePythonDocstrings(lines, out) {
  for (let i = 0; i < lines.length; i++) {
    const name = declarationAt(lines[i], 'python');
    if (!name) continue;
    // The docstring is the first statement of the body: scan past the
    // signature's continuation lines to the first non-blank, non-comment line.
    let j = i;
    while (j < lines.length && !/:\s*(#.*)?$/.test(lines[j])) j++;
    j++;
    while (j < lines.length && !lines[j].trim()) j++;
    if (j >= lines.length) continue;
    const open = /^\s*[rubfRUBF]*("""|''')/.exec(lines[j]);
    if (!open) continue;
    const quote = open[1];
    const startLine = j;
    let body = lines[j].slice(lines[j].indexOf(quote) + 3);
    if (body.includes(quote)) {
      body = body.slice(0, body.indexOf(quote));
    } else {
      j++;
      while (j < lines.length && !lines[j].includes(quote)) { body += '\n' + lines[j]; j++; }
      if (j < lines.length) body += '\n' + lines[j].slice(0, lines[j].indexOf(quote));
    }
    const text = clean(body);
    if (text.length >= MIN_RATIONALE_CHARS) {
      out.push({ text, line: startLine + 1, kind: 'docstring', ownerLine: i + 1, ownerName: name });
    }
  }
}

function parseBlockDocComments(lines, out) {
  for (let i = 0; i < lines.length; i++) {
    if (!/^\s*\/\*\*/.test(lines[i])) continue;
    const startLine = i;
    let body = lines[i];
    let j = i;
    while (j < lines.length && !lines[j].includes('*/')) { j++; if (j < lines.length) body += '\n' + lines[j]; }
    const text = clean(body.replace(/^\s*\/\*\*/, '').replace(/\*\/\s*$/, ''));
    // The documented declaration is the next line that looks like one,
    // skipping annotations.
    let k = j + 1;
    let ownerName = null;
    while (k < lines.length && k <= j + 6) {
      const t = lines[k].trim();
      if (!t || t.startsWith('@')) { k++; continue; }
      ownerName = declarationAt(lines[k], 'generic');
      break;
    }
    if (text.length >= MIN_RATIONALE_CHARS) {
      out.push({ text, line: startLine + 1, kind: 'docstring', ownerLine: ownerName ? k + 1 : null, ownerName });
    }
    i = j;
  }
}

/**
 * parseRationale(content, lang) -> [{ text, line, kind, ownerLine, ownerName }]
 * Never throws.
 */
function parseRationale(content, lang) {
  if (!content || typeof content !== 'string') return [];
  const out = [];
  const lines = content.split('\n');

  try {
    if (!isGenerated(content)) {
      if (DOCSTRING_LANGS.has(lang)) parsePythonDocstrings(lines, out);
      else if (BLOCK_COMMENT_LANGS.has(lang)) parseBlockDocComments(lines, out);
    }

    // Marker comments carry rationale wherever they sit, generated file or not
    // — a `# HACK:` in generated code is still a hack somebody has to know
    // about. Attributed to the nearest declaration ABOVE, so an explanation
    // inside a method belongs to that method.
    let lastDeclLine = null;
    let lastDeclName = null;
    for (let i = 0; i < lines.length; i++) {
      const decl = declarationAt(lines[i], lang === 'python' ? 'python' : 'generic');
      if (decl) { lastDeclLine = i + 1; lastDeclName = decl; }
      const t = lines[i].trim();
      if (!MARKER_RE.test(t)) continue;
      const text = clean(t.replace(/^(?:\/\/+|#+|\*|<!--)\s*/, '').replace(/-->\s*$/, ''));
      if (text.length < MIN_RATIONALE_CHARS) continue;
      out.push({ text, line: i + 1, kind: 'comment', ownerLine: lastDeclLine, ownerName: lastDeclName });
    }
  } catch (_) {
    return out;
  }

  // Same text repeated (a licence header, a copy-pasted caveat) is one fact.
  const seen = new Set();
  return out.filter((r) => {
    const key = r.text.slice(0, 160);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

module.exports = { parseRationale, MIN_RATIONALE_CHARS };
